import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/header/header";
import Footer from "./components/footer/footer";
import { CartProvider } from "./context/cartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bagel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <CartProvider>{children}</CartProvider>
      </body>
      <Footer/>
    </html>
  );
}
